name: Manual Workflow

on:
  workflow_dispatch: # Only runs manually

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "This workflow was triggered manually!"